# Generated by Django 4.2.11 on 2024-04-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BattingStats",
            fields=[
                (
                    "player_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("g", models.FloatField(blank=True, null=True)),
                ("pa", models.FloatField(blank=True, null=True)),
                ("hr", models.FloatField(blank=True, null=True)),
                ("r", models.FloatField(blank=True, null=True)),
                ("rbi", models.FloatField(blank=True, null=True)),
                ("sb", models.FloatField(blank=True, null=True)),
                ("bb_percentage", models.FloatField(blank=True, null=True)),
                ("k_percentage", models.FloatField(blank=True, null=True)),
                ("iso", models.FloatField(blank=True, null=True)),
                ("babip", models.FloatField(blank=True, null=True)),
                ("avg", models.FloatField(blank=True, null=True)),
                ("obp", models.FloatField(blank=True, null=True)),
                ("slg", models.FloatField(blank=True, null=True)),
                ("woba", models.FloatField(blank=True, null=True)),
                ("wrc_plus", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "batting_stats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Conferences",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("division_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "conferences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Divisions",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "divisions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PitchingStats",
            fields=[
                (
                    "player_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("g", models.FloatField(blank=True, null=True)),
                ("gs", models.FloatField(blank=True, null=True)),
                ("ip", models.FloatField(blank=True, null=True)),
                ("k_per_9", models.FloatField(blank=True, null=True)),
                ("bb_per_9", models.FloatField(blank=True, null=True)),
                ("hr_per_9", models.FloatField(blank=True, null=True)),
                ("babip", models.FloatField(blank=True, null=True)),
                ("era", models.FloatField(blank=True, null=True)),
                ("fip", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "pitching_stats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("grade", models.TextField(blank=True, null=True)),
                ("team_id", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "players",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("conference_id", models.IntegerField(blank=True, null=True)),
                ("g", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "teams",
                "managed": False,
            },
        ),
    ]
